name: Publish Package to PyPI
on:
  release:
    types: [created]
jobs:
  publish-to-pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install dependencies   
        run: |
          python -m pip install --upgrade build twine
      - name: Build distributions
        run: python -m build
      - name: Publish
        run: python3 -m twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
